### ISSUE TITLE
JMS: XA-only ConnectionFactory created for ActiveMQ Artemis

### ISSUE THREAD

**Issue by jensdt** [spring-cloud/spring-cloud-sleuth#1284]
When using ActiveMQ Artemis through JMS over remote JNDI, the connection factory we get back is an instance of org.apache.activemq.artemis.jms.client.ActiveMQJMSConnectionFactory. But as per  https://activemq.apache.org/artemis/docs/javadocs/javadoc-2.6.0/org/apache/activemq/artemis/jms/client/ActiveMQJMSConnectionFactory.html, you see this implements both javax.jms.ConnectionFactory and javax.jms.XAConnectionFactory. We want to use it in a non-XA fashion (we don't need XA transactions in our use case), but because of [this check](https://github.com/spring-cloud/spring-cloud-sleuth/blob/558900155adb1ae4a732cf450c216e2ff04a3f90/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TracingConnectionFactoryBeanPostProcessor.java#L73) we get a XA-only ConnectionFactory back after instrumentation with Brave.

IMHO this PostProcessor should be extended to create a bean that is also both an XA and non-XA connection factory if the instrumented bean is also both. If you agree this is a bug I'm open to fixing this myself with a PR - just let me know.

**Comment by bvoss** [comment]
a big 
+1
from my side.

It's very confusing to end up with an application startup failure by just adding the sleuth dependency with an error message regarding unsatisfied bean dependency.

> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jmsTemplate' defined in class path resource [JmsConfig.class]: Unsatisfied dependency expressed through method 'jmsTemplate' parameter 0; nested exception is org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'devConnectionFactory' is expected to be of type 'javax.jms.ConnectionFactory' but was actually of type  'org.springframework.cloud.sleuth.instrument.messaging.LazyXAConnectionFactory

but in the config you declare a bean of the correct type:

```
   @Bean("jmsConnectionFactory")
   public ConnectionFactory devConnectionFactory() {
        ConnectionFactory factory =  new ActiveMQJMSConnectionFactory(brokerURL, userName, password);
        LOGGER.info("Starting Artemis JMS connection to {}", brokerURL);
        return factory;
    }
```

**Comment by marcingrzejszczak** [comment]
Should be fixed via https://github.com/spring-cloud/spring-cloud-sleuth/commit/1b493e602a837536c6bccfa84c96ddf6ed169ca4  . Please check out the latest snapshots.

**Comment by jensdt** [comment]
I tested this with the latest 2.2.0.BUILD-SNAPSHOT, but still have the same issue. I also don't really see from the code change how this would be fixed. A bean that is both a javax.jms.ConnectionFactory and javax.jms.XAConnectionFactory will still be wrapped in a LazyXAConnectionFactory which is not a javax.jms.ConnectionFactory anymore.

```
Caused by: org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'jmsConnectionFactory' is expected to be of type 'javax.jms.ConnectionFactory' but was actually of type 'org.springframework.cloud.sleuth.instrument.messaging.LazyXAConnectionFactory'
```

You did fix 1324, but only if the bean isn't also an XAConnectionFactory. Else the error will remain for the same reason.

**Comment by marcingrzejszczak** [comment]
Ah true, thanks for pointing it out

**Comment by nick250386** [comment]
When using Sleuth for an application using AWS SQS messaging, I am getting an error, given below:
`
Caused by: java.lang.IllegalStateException: @Bean method JmsConfig.defaultConnectionFactory called as bean reference for type [com.amazon.sqs.javamessaging.SQSConnectionFactory] but overridden by non-compatible bean instance of type [org.springframework.cloud.sleuth.instrument.messaging.LazyConnectionFactory]. Overriding bean of same name declared in: class path resource [c/z/o/a/s/JmsConfig.class]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:418) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:366) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at c.z.o.a.s.JmsConfig$$EnhancerBySpringCGLIB$$8e92a374.defaultConnectionFactory(<generated>) ~[classes/:na]
	at c.z.o.a.s.JmsConfig.defaultJmsTemplate(JmsConfig.java:58) ~[classes/:na]
	at c.z.o.a.s.JmsConfig$$EnhancerBySpringCGLIB$$8e92a374.CGLIB$defaultJmsTemplate$2(<generated>) ~[classes/:na]
	at c.z.o.a.s.JmsConfig$$EnhancerBySpringCGLIB$$8e92a374$$FastClassBySpringCGLIB$$4ad44584.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at c.z.o.a.s.JmsConfig$$EnhancerBySpringCGLIB$$8e92a374.defaultJmsTemplate(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	... 76 common frames omitted
`
Does this mean that as per the commit [here](https://github.com/spring-cloud/spring-cloud-sleuth/commit/e099b6d9f40e7ac5afab58f77ccdf7773b1116a8), the library need to support AWS SQSConnectionFactory ?

Any pointers if I am missing something here ?

**Comment by marcingrzejszczak** [comment]
Please learn how to [properly format the code](https://help.github.com/articles/creating-and-highlighting-code-blocks/). Can you also provide which version of Sleuth you're using?

**Comment by nick250386** [comment]
My bad, I was trying to insert it properly using the '<>' control but seems like I made a mistake there. (I will try to rectify that.)Currently I am facing this issue with Sleuth version '2.1.0.RELEASE'

**Comment by marcingrzejszczak** [comment]
It's not the latest GA version of Sleuth available. Please upgrade to the latest and see if the problem persists.

**Comment by nick250386** [comment]
The Maven repository has dependency defined for '2.1.2.RELEASE' while the latest version of this library is '2.2.0'. Do you think it will work for '2.1.2.RELEASE' ?

**Comment by marcingrzejszczak** [comment]
Please test `2.1.2.RELEASE`. Typically before interacting with a closed issue you should verify whether the latest version works fine.

**Comment by nick250386** [comment]
Apologies if I deviated from the process.
Actually, I was able to get things running fine with the integration with the '2.1.0.RELEASE' version. I ran into issues when I ran JUnit test cases on it and it is then I got the above error I mentioned. I was not sure if I should have opened a new issue seeking support on this and I found this one relevant to my use case.

**Comment by nick250386** [comment]
**UPDATE**: With version '**2.1.2.RELEASE**' I continue to get the same error.

**Comment by marcingrzejszczak** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by nick250386** [comment]
Providing a sample would be difficult, but is there anything or any information that you are specifically looking for, that I can provide.

**Comment by nick250386** [comment]
I managed to create a sample spring boot application throwing the same error as I am encountering in my project. Along with it, I am also attaching the stacktrace of the exception that I am getting. Let me know if this helps.
[Error_Stacktrace.txt](https://github.com/spring-cloud/spring-cloud-sleuth/files/3349736/Error_Stacktrace.txt)
[demo.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/3349737/demo.zip)

**Comment by nick250386** [comment]
@marcingrzejszczak , do you think the issue I reported is a valid one or there is something wrong at my end. If possible, can you please share the proposed plan on this issue if it's a valid one ?

**Comment by marcingrzejszczak** [comment]
I'm sorry but I didn't have time to look into it but by the looks of it some code in your codebase is requiring a direct `SQSConnectionFactory` type. We're wrapping it in a tracing representation. That means that if you try to inject the `SQSConnectionFactory` you'll fail. If that's your code, can you use an interface instead of the concrete implementation?

**Comment by nick250386** [comment]
Can you help me in understanding how this wrapping works and what are you suggesting me to do ?

**Comment by adriancole** [comment]
tracing wrappers will reduce something like SQSxxx to ConnectionFactory.
Usually in Spring you will want to auto wire the more generic type that
your code needs. typically it doesnt need the implementation type. I think
more questions about this need to move to the gitter channel

**Comment by nick250386** [comment]
@marcingrzejszczak  / @adriancole , I gave a few attempts along the lines of your suggestions of using an interface to inject SQSConnectionFactory instead of a concrete implementation, but it seems like I am not getting the idea of how to do it. If possible, can give an example on how to achieve this based on the sample project that I provided.

**Comment by nick250386** [comment]
Apologies for delayed response.
I was able to solve the issue following the inputs given by @marcingrzejszczak  & @adriancole .
Instead of having a concrete return type of the method as 'SQSConnectionFactory', even though I continued to return an instance of 'SQSConnectionFactory' I changed the method signature to return 'ConnectionFactory'.

**EARLIER**:

```
public SQSConnectionFactory defaultConnectionFactory() {
		return new SQSConnectionFactory(new ProviderConfiguration(), AmazonSQSClientBuilder.standard().withRegion(Regions.fromName(awsRegion))
				.withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials(accessKey, secretKey))));
	}
```

**LATER**:
```
public ConnectionFactory defaultConnectionFactory() {
		return new SQSConnectionFactory(new ProviderConfiguration(), AmazonSQSClientBuilder.standard().withRegion(Regions.fromName(awsRegion))
				.withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials(accessKey, secretKey))));
	}
```
Please let me know if this is right or I should have tried something else.

**Comment by adriancole** [comment]
yep this is exactly right. and any use of the concrete SQS type would not
be traced. For example, if you affected the SQS factory before returning it
as a bean, any of that is ok, but it would not be traced.
