### ISSUE TITLE
After switching to Sleuth 3.0.2 TracerContext is always null

### ISSUE THREAD

**Issue by imochurad** [spring-cloud/spring-cloud-sleuth#1939]
I have upgraded Sleuth to version 3.0.2 and started getting NPEs in my codebase when running SpringBoot tests with mockMvc. 
I know that there were breaking changes, and there is a migration guide, but for the life of me, I cannot say how to resolve this issue.

Maven dependency:

```
    [INFO] +- org.springframework.cloud:spring-cloud-starter-sleuth:jar:3.0.2:compile
    [INFO] |  +- org.springframework.boot:spring-boot-starter-aop:jar:2.4.5:compile
    [INFO] |  |  \- org.aspectj:aspectjweaver:jar:1.9.6:compile
    [INFO] |  +- org.springframework.cloud:spring-cloud-sleuth-autoconfigure:jar:3.0.2:compile
    [INFO] |  |  +- org.springframework.cloud:spring-cloud-sleuth-instrumentation:jar:3.0.2:compile
    [INFO] |  |  |  \- org.springframework.cloud:spring-cloud-sleuth-api:jar:3.0.2:compile
    [INFO] |  |  \- org.aspectj:aspectjrt:jar:1.9.6:compile
    [INFO] |  \- org.springframework.cloud:spring-cloud-sleuth-brave:jar:3.0.2:compile
    [INFO] |     +- io.zipkin.brave:brave:jar:5.13.2:compile
    [INFO] |     +- io.zipkin.brave:brave-context-slf4j:jar:5.13.2:compile
    [INFO] |     +- io.zipkin.brave:brave-instrumentation-messaging:jar:5.13.2:compile
    [INFO] |     +- io.zipkin.brave:brave-instrumentation-rpc:jar:5.13.2:compile
    [INFO] |     +- io.zipkin.brave:brave-instrumentation-spring-rabbit:jar:5.13.2:compile
    [INFO] |     +- io.zipkin.brave:brave-instrumentation-kafka-clients:jar:5.13.2:compile
    [INFO] |     +- io.zipkin.brave:brave-instrumentation-kafka-streams:jar:5.13.2:compile
    [INFO] |     +- io.zipkin.brave:brave-instrumentation-httpclient:jar:5.13.2:compile
    [INFO] |     |  \- io.zipkin.brave:brave-instrumentation-http:jar:5.13.2:compile
    [INFO] |     +- io.zipkin.brave:brave-instrumentation-httpasyncclient:jar:5.13.2:compile
    [INFO] |     +- io.zipkin.brave:brave-instrumentation-jms:jar:5.13.2:compile
    [INFO] |     +- io.zipkin.brave:brave-instrumentation-mongodb:jar:5.13.2:compile
    [INFO] |     +- io.zipkin.aws:brave-propagation-aws:jar:0.21.3:compile
    [INFO] |     \- io.zipkin.reporter2:zipkin-reporter-metrics-micrometer:jar:2.16.1:compile
    [INFO] |        \- io.zipkin.reporter2:zipkin-reporter:jar:2.16.1:compile
    [INFO] |           \- io.zipkin.zipkin2:zipkin:jar:2.23.0:compile
```

The field that is being injected.

```
    @Autowired
    protected Tracer tracer;
```

The line that is throwing NPE:
    
`    tracer.currentSpan().context().traceId();`

The currentSpan() method, where ThreadContext is null.

```
    @Nullable
    public Span currentSpan() {
        TraceContext context = this.currentTraceContext.get();
        return context == null ? null : new LazySpan(this, context);
    }
```

Also this line is producing null: `String traceId = MDC.get("X-B3-TraceId");`

`MDC.getCopyOfContextMap();` returns an empty map.

Here is the code of the method for the completeness of the picture: 

    @GetMapping(path = "/user", produces = APPLICATION_JSON_VALUE)
    @RequiresPermissions(IAM_USER_GET_PERMISSION)
    public Object getMyself() {
        UserContext userContext = (UserContext) SecurityUtils.getSubject().getPrincipal();
        String traceId = MDC.get("X-B3-TraceId");
        System.out.println(traceId);
        System.out.println(MDC.getCopyOfContextMap());
        OperationContext operationContext = OperationContext.newInstance(userContext, tracer.currentSpan().context().traceId());
        UserBO user = identityManager.getMyself(operationContext);
        return ResponseEntity.status(HttpStatus.OK).body(new UserEnvelopeDTO(iamDTOMapper.mapScoped(user, user.getActiveOrganizationId())));
    }

As you can see this is an HTTP thread, that doesn't get MDC properly populated.

Also, I have this bean configured:

```
    @Bean
    public CurrentTraceContext.ScopeDecorator legacyMDCKeys() {
        return MDCScopeDecorator.newBuilder()
                .clear()
                .add(CorrelationScopeConfig.SingleCorrelationField.newBuilder(BaggageFields.TRACE_ID)
                        .name("X-B3-TraceId").build())
                .add(CorrelationScopeConfig.SingleCorrelationField.newBuilder(BaggageFields.PARENT_ID)
                        .name("X-B3-ParentSpanId").build())
                .add(CorrelationScopeConfig.SingleCorrelationField.newBuilder(BaggageFields.SPAN_ID)
                        .name("X-B3-SpanId").build())
                .add(CorrelationScopeConfig.SingleCorrelationField.newBuilder(BaggageFields.SAMPLED)
                        .name("X-Span-Export").build())
                .build();
    }
```

Please help me in this matter. I will be willing to provide all information in the world to get this issue fixed.

**Comment by marcingrzejszczak** [comment]
Please do not cross post https://stackoverflow.com/questions/67421939/after-switching-to-sleuth-3-0-2-tracercontext-is-always-null . Can you create a sample that replicates the problem?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by imochurad** [comment]
Please use the project below, I have quite a complex dependency chain with parent maven projects, I dumbed it down to the bare minimum: 
https://github.com/imochurad/sleuth-test
You will find there a test that is failing. 
Looking forward for your feedback.

**Comment by imochurad** [comment]
Any chance this issue gets some traction? Thanks.

**Comment by marcingrzejszczak** [comment]
I saw your example - it's related to Brave not Sleuth. You should call `traceIdString()` method not `traceId()`. BTW if you use Sleuth's API the code works fine. Also I've fixed your code cause it always fails

```java
package com.company;

import org.slf4j.MDC;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cloud.sleuth.Tracer;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;

@RestController
@Validated
@RequestMapping("/api/v0")
public class Controller {

    @Autowired
    private Tracer tracer;

    @Autowired
    private brave.Tracer braveTracer;

    @GetMapping(path = "/user", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity get() {
        try {
            String traceId = MDC.get("X-B3-TraceId");
            System.out.println(traceId);
            System.out.println(MDC.getCopyOfContextMap());
            tracer.currentSpan().context().traceId();
            braveTracer.currentSpan().context().traceIdString();
        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
        return ResponseEntity.status(HttpStatus.OK).build();
    }

}
```

**Comment by imochurad** [comment]
@marcingrzejszczak How did you fix it? 
I still get NPE there with your code copied into my IntelliJ. 
Did you run the test? `SomeTest` ? It fails because the MDC context is always empty.
Also, even the first statement produces `null`:?
```
2021-05-25 20:23:06.190  INFO [,,] 56553 --- [           main] o.s.t.web.servlet.TestDispatcherServlet  : Completed initialization in 1 ms
null
null
```
What do you mean by using Sleuth's API?

**Comment by marcingrzejszczak** [comment]
In Sleuth 3.x we've removed the `X-B3-TraceId` entry from MDC - please read the docs: https://github.com/spring-cloud/spring-cloud-sleuth/wiki/Spring-Cloud-Sleuth-3.0-Migration-Guide#x-b3--mdc-fields-names-are-no-longer-set

Please see the code below with fully functional code 

```java
package com.company;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.slf4j.MDC;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cloud.sleuth.Tracer;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;

@RestController
@RequestMapping("/api/v0")
public class Controller {

    private static final Logger log = LoggerFactory.getLogger(Controller.class);

    @Autowired
    private Tracer tracer;

    @Autowired
    private brave.Tracer braveTracer;

    @GetMapping(path = "/user", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity get() {
        try {
            String traceId = MDC.get("traceId");
            log.info(traceId);
            log.info("" + MDC.getCopyOfContextMap());
            tracer.currentSpan().context().traceId();
            braveTracer.currentSpan().context().traceIdString();
        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
        return ResponseEntity.status(HttpStatus.OK).build();
    }

}
```

you can notice that `Tracer` comes directly from Sleuth. This is what I mean by Sleuth's API.

If you run the app it works fine - The fact that the test doesn't work for you in the test is that because MockMvc doesn't have the tracing filter applied. I fixed the test for you

```java
package com.company;

import org.assertj.core.api.BDDAssertions;
import org.junit.Test;
import org.junit.runner.RunWith;

import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.web.server.LocalServerPort;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.web.client.RestTemplate;

@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class SomeTest {

    @LocalServerPort
    int port;

    @Test
    public void test() throws Exception {
        ResponseEntity<String> responseEntity = new RestTemplate().getForEntity("http://localhost:" + port + "/api/v0/user", String.class);

        BDDAssertions.then(responseEntity.getStatusCodeValue()).isEqualTo(200);
    }

}

```

then you can check the logs

```
2021-05-26 08:35:28.549  INFO [,aa5269cf0ac7cc03,aa5269cf0ac7cc03] 389634 --- [o-auto-1-exec-1] com.company.Controller                   : aa5269cf0ac7cc03
2021-05-26 08:35:28.550  INFO [,aa5269cf0ac7cc03,aa5269cf0ac7cc03] 389634 --- [o-auto-1-exec-1] com.company.Controller                   : {traceId=aa5269cf0ac7cc03, spanId=aa5269cf0ac7cc03}
```

**Comment by imochurad** [comment]
@marcingrzejszczak I see what you did there with the RestTemplate, as far as I understand in this case you do not have to configure additional filters, as you are placing a request against a running server.
But the thing is, I cannot simply move to the RestTemplate as I am heavily relying on the MockMvc, could you please help with the configuration of the Sleuth Filter for MockMvc? I would really appreciate it.
Thanks!

**Comment by imochurad** [comment]
Actually, I made it work:

```
    @Before
    @SuppressWarnings("raw")
    public void setupMockMvc() {
        Collection<Filter> filters = webApplicationContext.getBeansOfType(Filter.class).values();
        Collection<FilterRegistrationBean> filterRegistrationBeans = webApplicationContext.getBeansOfType(FilterRegistrationBean.class).values();
        List<Filter> allFilters = new ArrayList<>(filters);
        allFilters.addAll(filterRegistrationBeans.stream().map(FilterRegistrationBean::getFilter).collect(Collectors.toList()));
        mockMvc = MockMvcBuilders
                .webAppContextSetup(webApplicationContext)
                .addFilters(allFilters.toArray(new Filter[0]))
                .build();
    }
```

**Comment by fisco-unimatic** [comment]
For me, the particular filter that I needed to add was 'traceWebFilter' from the TraceWebServletConfiguration.

    .addFilter(webApplicationContext.getBean("traceWebFilter", FilterRegistrationBean.class).getFilter())
