### ISSUE TITLE
Spring Cloud Sleuth not compatible with Spring Boot 2.7.0-SNAPSHOT

### ISSUE THREAD

**Issue by coolbananas118** [spring-cloud/spring-cloud-sleuth#2111]
I'm trying to add Spring GraphQL to an existing project however Spring Cloud Sleuth dependency is causing error "Spring Boot [2.7.0-SNAPSHOT] is not compatible with this Spring Cloud release train"

My project has the following Gradle dependency and if I comment it out the bug goes away.
`implementation 'org.springframework.cloud:spring-cloud-starter-sleuth:3.1.0'`

I also tried with Sleuth version 3.1.1-SNAPSHOT but get the same error.

A simple way to reproduce it is to add the dependency to the following project and try to start it via `bootRun` and you'll get the same error.
https://github.com/spring-projects/spring-graphql/tree/main/samples/webflux-websocket

**Comment by marcingrzejszczak** [comment]
Duplicate of https://github.com/spring-cloud/spring-cloud-commons/issues/1049

**Comment by spencergibb** [comment]
@coolbananas118 the latest 3.1.1-SNAPSHOT should work now that I've updated commons. Previous releases will not work. Official 2.7 support will be part of [2021.0.4](https://github.com/spring-cloud/spring-cloud-release/milestone/121) in May after boot 2.7 is released.

**Comment by coolbananas118** [comment]
@spencergibb doesn't seem to work. I dropped 3.1.1-SNAPSHOT from my Gradle cache (~/.gradle/caches/modules-2/files-2.1/org.springframework.cloud/spring-cloud-sleuth) and did a re-run and still get the error. If I comment out the dependency (implementation 'org.springframework.cloud:spring-cloud-starter-sleuth:3.1.1-SNAPSHOT') it is fine.

**Comment by marcingrzejszczak** [comment]
You should ensure that you have the latest spring-cloud-commons snapshots, not Sleuth snapshots.
