### ISSUE TITLE
Sleuth: span and trace are not present in the response log, only in request

### ISSUE THREAD

**Issue by taxone** [spring-cloud/spring-cloud-sleuth#2242]
**Describe the bug**
Spring boot 2.6.4
Spring Cloud 2021.0.1
Added the Sleuth dependency and enabled *instrumentation-type*:

```
spring.sleuth.reactor.instrumentation-type: decorate-on-each
```

The span and trace identifiers are only present in the request log, but not in the response:

```
2022-03-10 09:20:40.220[0;39m [32mDEBUG [sleuth-poc,e6b60512cdeacd74,e6b60512cdeacd74][0;39m [35m19360[0;39m [2m---[0;39m [2m[ctor-http-nio-4][0;39m [36mo.s.c.g.h.RoutePredicateHandlerMapping  [0;39m [2m:[0;39m Route matched: myrule
[2m2022-03-10 09:20:40.220[0;39m [32mDEBUG [sleuth-poc,e6b60512cdeacd74,e6b60512cdeacd74][0;39m [35m19360[0;39m [2m---[0;39m [2m[ctor-http-nio-4][0;39m [36mo.s.c.g.h.RoutePredicateHandlerMapping  [0;39m [2m:[0;39m Mapping [Exchange: GET http://localhost:8081/apigw/get] to Route{id='myrule', uri=https://httpbin.org:443, order=0, predicate=Paths: [/apigw/get/**], match trailing slash: true, gatewayFilters=[[[RewritePath /apigw(?<segment>/?.*) = '${segment}'], order = 1]], metadata={}}
[2m2022-03-10 09:20:40.220[0;39m [32mDEBUG [sleuth-poc,e6b60512cdeacd74,e6b60512cdeacd74][0;39m [35m19360[0;39m [2m---[0;39m [2m[ctor-http-nio-4][0;39m [36mo.s.c.g.h.RoutePredicateHandlerMapping  [0;39m [2m:[0;39m [116abe06-3] Mapped to org.springframework.cloud.gateway.handler.FilteringWebHandler@67dceb32
[2m2022-03-10 09:20:40.221[0;39m [32mDEBUG [sleuth-poc,e6b60512cdeacd74,e6b60512cdeacd74][0;39m [35m19360[0;39m [2m---[0;39m [2m[ctor-http-nio-4][0;39m [36mo.s.c.g.handler.FilteringWebHandler     [0;39m [2m:[0;39m Sorted gatewayFilterFactories: [[GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.RemoveCachedBodyFilter@26c89563}, order = -2147483648], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.AdaptCachedBodyGlobalFilter@358ab600}, order = -2147482648], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.NettyWriteResponseFilter@2a8a4e0c}, order = -1], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.ForwardPathFilter@20f6f88c}, order = 0], [[RewritePath /apigw(?<segment>/?.*) = '${segment}'], order = 1], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.RouteToRequestUrlFilter@3bd6ba24}, order = 10000], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.config.GatewayNoLoadBalancerClientAutoConfiguration$NoLoadBalancerClientFilter@4c7e978c}, order = 10150], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.WebsocketRoutingFilter@4277127c}, order = 2147483646], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.NettyRoutingFilter@20d87335}, order = 2147483647], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.ForwardRoutingFilter@58f437b0}, order = 2147483647]]
[2m2022-03-10 09:20:40.769[0;39m [32mDEBUG [sleuth-poc,,][0;39m [35m19360[0;39m [2m---[0;39m [2m[ctor-http-nio-4][0;39m [36mr.netty.http.client.HttpClientConnect   [0;39m [2m:[0;39m [a16ba65b-1, L:/192.168.1.109:59032 - R:httpbin.org/54.221.78.73:443] Handler is being applied: {uri=https://httpbin.org/get, method=GET}
[2m2022-03-10 09:20:40.890[0;39m [32mDEBUG [sleuth-poc,,][0;39m [35m19360[0;39m [2m---[0;39m [2m[ctor-http-nio-4][0;39m [36mr.n.http.client.HttpClientOperations    [0;39m [2m:[0;39m [a16ba65b-1, L:/192.168.1.109:59032 - R:httpbin.org/54.221.78.73:443] Received response (auto-read:false) : [Date=Thu, 10 Mar 2022 08:20:40 GMT, Content-Type=application/json, Connection=keep-alive, Server=gunicorn/19.9.0, Access-Control-Allow-Origin=*, Access-Control-Allow-Credentials=true, content-length=623]
[2m2022-03-10 09:20:40.891[0;39m [32mDEBUG [sleuth-poc,,][0;39m [35m19360[0;39m [2m---[0;39m [2m[ctor-http-nio-4][0;39m [36mr.n.http.client.HttpClientOperations    [0;39m [2m:[0;39m [a16ba65b-1, L:/192.168.1.109:59032 - R:httpbin.org/54.221.78.73:443] Received last HTTP packet
```

**Sample**
The sample project is [here](https://github.com/taxone/poc-sleuth).

**Comment by person2713** [comment]
any news?

**Comment by marcingrzejszczak** [comment]
@violetagg have we been working on that in Reactor Netty?

**Comment by violetagg** [comment]
@marcingrzejszczak This does not use the Reactor Netty <-> Brave integration but the integration in Sleuth.

**Comment by marcingrzejszczak** [comment]
Maybe that's the reason why it's not working. We don't instrument things on the Reactor Netty level out of the box in Sleuth (for the response log)?

**Comment by violetagg** [comment]
> Maybe that's the reason why it's not working. We don't instrument things on the Reactor Netty level out of the box in Sleuth (for the response log)?

This is the client I was thinking that for the client you instrument everything?
https://github.com/spring-cloud/spring-cloud-sleuth/blob/c795675cf93c666c3c13f9bbb9eadbde1f1aa775/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/HttpClientBeanPostProcessor.java#L75

**Comment by marcingrzejszczak** [comment]
Erm, I've clearly forgotten about this one :grimacing: I'll need to take a look into what's going on. BTW @taxone have you tried the latest snapshots? We fixed a few things Reactor related

**Comment by taxone** [comment]
@marcingrzejszczak I just upgraded the sample project to the latest Spring Boot and Spring Cloud versions, but the problem persists:

https://github.com/taxone/poc-sleuth

**Comment by ducanh2110** [comment]
Describe the bug
Spring boot 2.7.13
Spring Cloud 2021.0.8
Added the Sleuth dependency and enabled instrumentation-type:

spring.sleuth.reactor.instrumentation-type: decorate-on-each
Sample problem with the authors. Only have traceId for the request after it changed to another threads to proc the request no more traceId anymore but it have another traceId on itself.

any more support for this issue?

**Comment by marcingrzejszczak** [comment]
I guess I'll need @OlegDokuka 's help

**Comment by marcingrzejszczak** [comment]
Please upgrade to [Micrometer Tracing](https://docs.micrometer.io/tracing/reference/). Spring Cloud Sleuth is feature complete and out of OSS support.
