### ISSUE TITLE
1.0.4 : SleuthHystrixFeignBuilder does not work with custom ErrorDecoder

### ISSUE THREAD

**Issue by bitsofinfo** [spring-cloud/spring-cloud-sleuth#374]
https://github.com/spring-cloud/spring-cloud-sleuth/blob/v1.0.4.RELEASE/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/SleuthHystrixFeignBuilder.java

I have a @FeignClient (or @EnableFeignClients) custom configuration that specifies  my custom `ErrorDecoder` @Bean. 

If my project uses spring-cloud-sleuth, the ErrorDecoder that is actually used is always `TraceFeignErrorDecoder`

Seems like this should be constructed with the `delegate` version of the constructor that grabs any existing bean that is configured for the ErrorDecoder rather than the hardwired `Default` ErrorDecoder

https://gitter.im/spring-cloud/spring-cloud?at=57b21a201a7d020756817960

**Comment by spencergibb** [comment]
I believe this is already fixed here https://github.com/spring-cloud/spring-cloud-sleuth/commit/ecdf32c5bc823ae1c10f3c1d2739928f7cde0fdf. @marcingrzejszczak can confirm.

**Comment by bitsofinfo** [comment]
Any thoughts on a workaround for 1.0.4 in the meantime? Trying to hack something up on my own, but open to suggestions from the experts

**Comment by bitsofinfo** [comment]
I tried my own hack to fix this for my 1.0.4 app that needs this functionality to no avail. I declared my own `ErrorDecoder` bean in my main app config class and in several of my custom @FeignClient configurations.

```
public class TraceFeignClientAutoConfiguration {

        ....

	@Autowired(required=false)
	private ErrorDecoder errorDecoder;

	@Bean
	@Scope("prototype")
	@ConditionalOnClass(HystrixCommand.class)
	@ConditionalOnProperty(name = "feign.hystrix.enabled", matchIfMissing = true)
	Feign.Builder feignHystrixBuilder(BeanFactory beanFactory) {
		
		// BEGIN HACK
		///
		TraceFeignErrorDecoder feignErrorDecoder;
		if (errorDecoder == null) {
			feignErrorDecoder = new TraceFeignErrorDecoder(beanFactory);
		} else {
			feignErrorDecoder = new TraceFeignErrorDecoder(beanFactory,errorDecoder);
		}
		
		return HystrixFeign.builder()
				.client(new TraceFeignClient(beanFactory))
				.retryer(new TraceFeignRetryer(beanFactory))
				.decoder(new TraceFeignDecoder(beanFactory))
				.errorDecoder(feignErrorDecoder);
		///
		// END HACK
		
		// BUG return SleuthHystrixFeignBuilder.builder(beanFactory);
	}
```

**Comment by marcingrzejszczak** [comment]
Yeah it's been fixed in that commit. I'm doing small adjustments ATM and adding a more explicit test to ensure that things are working.

**Comment by marcingrzejszczak** [comment]
@bitsofinfo can you show how you register your `ErrorDecoder` ?

**Comment by bitsofinfo** [comment]
In this case (Brixton.SR4) MyConfig.class's @Bean construction methods never get invoked (constructed)

```
@FeignClient(name="my-service", 
            decode404=true,
            fallback = MyFallback.class,
            configuration=MyConfig.class)
public interface MyClient {

    @RequestMapping(method=RequestMethod.GET, value = "/my/path/{x}", produces = "application/json")
    public ResponseEntity<? extends Object> getSomething(@PathVariable("x") String x);
}
```

MyConfig.class
```
@Configuration
public class MyConfig {

    @Bean 
    public Logger.Level loggerLevel() {
        return Logger.Level.BASIC;
    }

    @Bean
    public ErrorDecoder errorDecoder() {
        return new MyErrorDecoder();
    }
```

The only way I can get the @Bean created (however its still not actually invoked at runtime due to this bug described above) is like this. 

```
@Configuration
@EnableFeignClients(clients={MyClient.class}, 
                    defaultConfiguration=MyConfig.class)
public class MyConfigClass {
...
```

**Comment by marcingrzejszczak** [comment]
I've written a test for the current 1.0.x branch (1.0.5.BUILD-SNAPSHOT) - https://github.com/spring-cloud/spring-cloud-sleuth/blob/f677be026e0aa4dd41187cc9408421ba670463ba/spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/issues/issue362/Issue362Tests.java#L167 and it's working fine. Can you switch to Brixton Snapshot version of the BOM and check this out?

**Comment by bitsofinfo** [comment]
Yes this appears to work now without my hack using the snapshot.
