### ISSUE TITLE
Instrument websocket with STOMP protocol

### ISSUE THREAD

**Issue by gravitycode** [spring-cloud/spring-cloud-sleuth#716]
Hi!
im trying to instrument STOMP messages with Websockets. The problem is that the traceId and spanId headers doesnt send to the broker (RabbitMQ). I was debugging the TraceChannelInterceptor class and the method preSend inject this parameters as headers but not as nativeHeaders. it seems that when sending messages to RabbitMQ only the native headers will send.

Those are the Headers that i can see before return the preSend method:
```
StompHeaderAccessor [
headers={simpMessageType=MESSAGE, 
simpSessionAttributes={SPRING.SESSION.ID=68e42f8a-209a-48fe-ba1c-5730e160bbc1}, 
simpHeartbeat=[J@6f0110ca, messageSent=true, 
simpUser=org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationToken@147badd3: 
Principal: com.cp.security.siteminder.SiteMinderUserDetails[username: E, authorities: [ROLE_admin, ROLE_read], 
entitlementsAsRoles: true]; 
Credentials: [PROTECTED]; 
Authenticated: true; 
Details: com.cp.security.siteminder.SiteMinderWebAuthenticationDetails@957e: 
RemoteIpAddress: 127.0.0.1; SessionId: null; Granted Authorities: 
ROLE_admin, ROLE_read, 
simpDestination=/exchange/worker.wm/app, 
spanTraceId=37fc95836f022908, 
spanId=dcdd3be3be35f983,
stompCommand=SEND, 
nativeHeaders={content-type=[application/json], 
correlationId=[13], reply-to=[/temp-queue/reply], 
destination=[/exchange/worker.wm/app.], 
content-length=[96]}, spanSampled=0, 
contentType=application/json, 
simpSessionId=ka3fepdp}]
```
You can see in the headers:
**spanTraceId=37fc95836f022908, 
spanId=dcdd3be3be35f983,**

In RabbitMQ the message appears:
<img width="469" alt="captura de pantalla 2017-09-28 a las 10 18 08" src="https://user-images.githubusercontent.com/8099955/30956124-6ffe2418-a436-11e7-83f6-17a08658f64c.png">

With this behavior i cant continue the spanTraceId in the consumer side.
How could i change this behavior?

Thank you :)

EDIT:

It seems that stomp is not supported by sleuth since the headers differ in standard messages. I need to map the Span trace Id to nativeHeaders. What would be the best way to change this behavior?

**Comment by dsyer** [comment]
Can you post a simple sample app, please, and explain how to recreate the behaviour above?

**Comment by gravitycode** [comment]
@dsyer I found the problem. The sleuth websocket implementation doesnt support Stomp message. Stomp Message when is passed to RabbitMQ only pass native headers and sleuth insert this properties in headers. The workaround is change the TraceChannelInterceptor.preSend behavior to introduce in native headers the spanTraceId and spanId properties.

```
Message<?> sleuthMessage = super.preSend(msg, channel);
StompHeaderAccessor accessor = MessageHeaderAccessor.getAccessor(msg, StompHeaderAccessor.class);
accessor.addNativeHeader(TraceMessageHeaders.TRACE_ID_NAME, (String)sleuthMessage.getHeaders().get(TraceMessageHeaders.TRACE_ID_NAME));
accessor.addNativeHeader(TraceMessageHeaders.SPAN_ID_NAME, (String)sleuthMessage.getHeaders().get(TraceMessageHeaders.TRACE_ID_NAME));
return MessageBuilder.createMessage(msg.getPayload(), accessor.getMessageHeaders());
```
the super.preSend() call can be deleted and use the the sleuth beans to generate traces ids.

**Comment by dsyer** [comment]
That's what this line is supposed to do: https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/MessagingTextMap.java#L66. Can you explain why that's not working as expected? A test case would be awesome.

**Comment by gravitycode** [comment]
Its seem that accesor never will be an instance of NativeHeaderAccesor. I will do a test using a java sockjs client.

**Comment by dsyer** [comment]
The client has no influence. There must be a bug somewhere. The native access is created too late or something.

**Comment by dsyer** [comment]
But if you can use the java client, I guess maybe we can at least get a unit test?

**Comment by gravitycode** [comment]
i will do a test :)

**Comment by gravitycode** [comment]
The example does not use the relay broker for simplicity. The problem is the same with the simple broker.

https://github.com/gravitycode/sleuth-websocket

Please read the instructions :P

**Comment by dsyer** [comment]
Thanks. I traced the flow of that message using the debugger. In Spring Messaging inside `SendToMethodReturnValueHandler.handleReturnValue()` the message headers are basically discarded (even the "native" ones), so we may need to see if Spring Messaging ever intended to support header propagation. Is it even part of the STOMP protocol?

**Comment by rstoyanchev** [comment]
If message is routed to a controller, any messages sent from the controller by definition have a different destination and target recipients. So it doesn't make sense for `SendToMethodReturnValuehandler` to automatically propagate headers from the source message.

I don't know what the Sleuth implementation does for this but I imagine it would have to use an `ExecutorChannelInterceptor` on the client inbound message channel to set the trace information from the source message, and then also on the broker channel to propagate on target messages.

The STOMP protocol does support custom headers on messages.

**Comment by dsyer** [comment]
See: https://jira.spring.io/browse/SPR-16031

**Comment by rstoyanchev** [comment]
I'm moving the discussion back here. Can you explain what channels are intercepted or point me to the code that does that?

**Comment by dsyer** [comment]
The interceptor is here: https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceChannelInterceptor.java. It adds span headers to an outgoing message if they don't already exist. I'm not 100% sure how it gets added to the message channels.Spring Integration just adds beans of interceptor types to all channels, I think, but I don't know how the vanilla Spring Messaging pieces work.

Don't you agree that `SendToMethodReturnValueHandler` discards headers? I think Spring AMQP (or perhaps Spring Integration) has an API/convention for headers to propagate, as opposed to keeping them in process. Maybe we could copy that in Spring Messaging?

**Comment by gravitycode** [comment]
I have been running different tests communicating two applications through messaging using RabbitMQ as broker. The tests are done by modifying the channelInterceptor that sends the message the preSend() method to add the spanId and spanTraceId headers explicitly. Service 2 uses int-amqp: inbound-gateway to consume and produce messages to the broker.

With this modification, the service 2 receives the headers correctly but I find that if I do not explicitly declare the mapping of these headers in the inbound-gateway, it generates new traceId and does not use those received.

```
		<int-amqp:inbound-gateway 
			request-channel="rabbitInput"
			reply-channel="rabbitOutput"
			error-channel="errorChannel"
			listener-container="listenerContainer" />
```

The flow message is:
Service 1 ---> RabbitMQ --> Service 2 ---> RabbitMQ ----> Service 1

SERVICE 1
CALL (1) {"spanTraceId":"**7119ea2b677d843d**","spanId":"86b10ef4cbc140eb"}
....
RESPONSE (4) {"spanTraceId":"**b4df301011ba7982**","spanId":"b4df301011ba7982"}

SERVICE 2
[REQUEST] (2) **spanTraceId=260133c23c23b34c**, spanId=260133c23c23b34c, spanParentSpanId=260133c23c23b34c, 
[RESPONSE] (3) **spanTraceId=260133c23c23b34c**, spanId=260133c23c23b34c, spanParentSpanId=260133c23c23b34c

If i map the headers in the inbound-gateway then it makes use of them and uses them correctly except in the response. The headers are not injected in the response again. 

```
		<int-amqp:inbound-gateway 
			request-channel="rabbitInput"
			reply-channel="rabbitOutput"
			error-channel="errorChannel"
			mapped-request-headers="spanTraceId,spanId"
			mapped-reply-headers="spanTraceId,spanId"
			listener-container="listenerContainer" />
```

SERVICE 1
CALL (1) {"spanTraceId":"1a02ca03f2c333a3","spanId":"c1bca171a0998efc"}
.....
RESPONSE (4) {"spanTraceId":"b0d1e5588a3031a4","spanId":"b0d1e5588a3031a4"}

<img width="674" alt="captura de pantalla 2017-10-02 a las 10 45 45" src="https://user-images.githubusercontent.com/8099955/31071182-5e822c68-a763-11e7-8652-7bd7069b5517.png">

SERVICE 2 
REQUEST (2)-> headers -> spanId=1a02ca03f2c333a3, spanTraceId=1a02ca03f2c333a3
RESPONSE(4) -> headers -> spanId=1a02ca03f2c333a3, spanTraceId=1a02ca03f2c333a3

This is the response message published in the broker by service 2. The spanId and spanTraceId are not presented.
<img width="486" alt="captura de pantalla 2017-10-02 a las 11 12 40" src="https://user-images.githubusercontent.com/8099955/31070972-a9f65512-a762-11e7-9182-a508a5f3df52.png">

I wonder if I have been able to publish properties in the headers, would not it be enough to modify the span extractor and injector so that they work correctly in this case? I added the headers explicitly in my modified channel interceptor and they were published in the broker.

**Comment by dsyer** [comment]
Can you clarify the diagram above (or better yet, push a sample app that shows the whole flow)? How does Service1 send the message to Rabbit? (I assume the inbound gateway is in Service2.)

**Comment by gravitycode** [comment]
You assume well. I can share with you for example a service 2 implementation but, do you prefer using RabbitMQ or in memory queues?

This is the full flow im using.
![slice](https://user-images.githubusercontent.com/8099955/31077892-87dfb16c-a780-11e7-9a26-a89a31a5493c.png)

the red stars indicate the hot points of extraction and injection of the headers. The number one (which is what we are mainly discussing here) i temporarily solved modifying the preSend of the TraceChannelInterceptor. The number 2 works if i add in the inbound trace properties in "mapped-request-headers".  The number 3 i think that need the same as number 1. Finally, the number 4 does not receive headers yet.

**Comment by rstoyanchev** [comment]
> I'm not 100% sure how it gets added to the message channels... I don't know how the vanilla Spring Messaging pieces work.

The `@EnableWebSocketMessageBroker` configuration creates 3 channels -- clientInboundChannel, clientOutboundChannel, and brokerChannel. You can see [an overview here](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#websocket-stomp-message-flow) of how messages flow across WebSocket server, controllers, and the broker. 

A `WebSocketMessageBrokerConfigurer` can configure those channels individually and install interceptors. I found the one for Sleuth [right here](https://github.com/spring-cloud/spring-cloud-sleuth/blob/2f6a8df5fe620527720951b925d7ca3570517604/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/websocket/TraceWebSocketAutoConfiguration.java#L56-L64). It looks like it only targets the WebSocket server channels but not the broker channel. I wonder why?

When a `@Controller` receives a message  from a WebSocket client, that controller is the final destination. This is not a request-reply pattern. The controller is then free to create and generate more messages but do not automatically assume that headers from the source message apply to messages sent from the controller. 

By not instrumenting the broker channel, by the way, you're also not going propagate anything headers from `@RequestMapping` methods that use the `SimpMessagingTemplate` to send messages. This is just another variation on the same issue IMO.

**Comment by gravitycode** [comment]
The contents in the inbound gateway documentation i think maybe can help us understand what´s going on.

"By default only standard AMQP properties (e.g. contentType) will be copied to and from Spring Integration MessageHeaders. Any user-defined headers within the AMQP`MessageProperties` will NOT be copied to or from an AMQP Message by the default DefaultAmqpHeaderMapper"

(https://docs.spring.io/spring-integration/reference/html/amqp.html#amqp-inbound-gateway)

**Comment by dsyer** [comment]
> It looks like it only targets the WebSocket server channels but not the broker channel. I wonder why?

Probably because we are ignorant. I don't see any methods in there that look like they deal with the `brokerChannel`. How would you add an interceptor to that?

**Comment by rstoyanchev** [comment]
It's there under `configureMessageBroker`. The `MessageBrokerRegistry` has a `configureBrokerChannel()` method.

**Comment by gravitycode** [comment]
I have detected another problem in Star 4 (diagram). The HeaderBasedMessagingExtractor.joinTrace method involved extracting the traceId and and the spanTraceId in my case receives these headers as nativeHeaders so it generates new identifiers.

This is the message received from RabbitMQ:
```
{contentType=text/plain, 
nativeHeaders={
subscription=[/temp-queue/reply], 
destination=[/queue/amq.gen-HpKP4Bp0yyhpibjCz46NdA], 
message-id=[T_/temp-queue/reply@@session-eJvDK_dNguI4N9tlFuNqMg@@2], 
redelivered=[false], 
spanTraceId=[a3e7c739a5b6a609], 
spanId=[a3e7c739a5b6a609], correlationId=[6], 
priority=[0], persistent=[true], 
content-encoding=[UTF-8], 
content-type=[text/plain], 
content-length=[550]}, 
simpDestination=/queue/amq.gen-HpKP4Bp0yyhpibjCz46NdA, 
simpMessageType=MESSAGE, simpSessionId=d0riurtn, 
simpSubscriptionId=/temp-queue/reply, 
Granted Authorities: ROLE_admin, ROLE_read, stompCommand=MESSAGE}
```
I think it's all about modifying the injectors and extractors and also reviewing the propagation of identifiers since many of the messaging pieces ignore the non-standard properties.

**Comment by gravitycode** [comment]
After having been testing, I think the problem is in the injection and extraction of properties with changes of protocol (Stomp - Spring messaging).

MessagingSpanTextMapInjector
When we inject we need to pass traceId and spanTraceId on the native headers but this does not happen but they are injected into the headers and therefore do not propagate.

MessagingSpanTextMapExtractor
When we extract properties we need to read traceId and spanTraceId from the native headers and write them in the headers so that the interceptor can find them and this does not happen.

I tried to create my own injector but with the SpanTextMap interface I can barely do anything to add the native headers to the trace identifiers.

**Comment by dsyer** [comment]
Should be fixed in 85d81515922. There doesn't seem to be a reliable way to only set native headers when the messages are websocket-related because the native headers might not be available at the time the interceptor is executing. So we have to add all span headers as "native" even if there is no concept of "native" in the underlying framework.

**Comment by rstoyanchev** [comment]
@dsyer I don't see why that is the case. First when the interceptors are installed through WebSocketMessageBrokerConfigurer you're pretty much know it's going to be all STOMP over WebSocket messaging. Second, if you don't want to parameterize the interceptor code, or perhaps the code that does this is too far to pass a property, you can always check if the message is related to STOMP messaging:
```
SimpMessageHeaderAccessor accessor =
    MessageHeaderAccessor.getAccessor(message, SimpMessageHeaderAccessor.class);

if (accessor !=null) {
    // Add native headers..
}
```

**Comment by gravitycode** [comment]
I have taken up this issue and i can see that the transform of headers to nativeHeaders was resolved but from nativeHeaders to headers still not working.

I have to do in a message interceptor:

`
    @Override
    public Message<?> preSend(Message<?> msg, MessageChannel channel) {

        StompHeaderAccessor accessor = MessageHeaderAccessor.getAccessor(msg, StompHeaderAccessor.class);
        Message<?> message = null;

        // from nativeHeaders -> to -> headers
        if(StompCommand.MESSAGE.equals(accessor.getCommand())){
            accessor = StompHeaderAccessor.wrap(msg);
            String traceId = accessor.getFirstNativeHeader(TraceMessageHeaders.TRACE_ID_NAME);
            String spanTraceId = accessor.getFirstNativeHeader(TraceMessageHeaders.SPAN_ID_NAME);

            Map<String, String> traceHeaders = new HashMap<String, String>();
            traceHeaders.put(TraceMessageHeaders.TRACE_ID_NAME, traceId);
            traceHeaders.put(TraceMessageHeaders.SPAN_ID_NAME, spanTraceId);

            accessor.copyHeadersIfAbsent(traceHeaders);
            message = super.preSend(new GenericMessage<>(msg.getPayload(), accessor.getMessageHeaders()), channel);
        } else {
            message = super.preSend(msg, channel);     
        }

        return message;
       
    }
`
